import {
  Check,
  Close,
  Delete,
  Plus,
  ArrowDown,
  ArrowUp,
  ArrowRight,
  ArrowLeft,
  ShoppingCart,
  Camera,
  View,
  Warning,
  Help,
  Edit,
  InfoFilled,
  User,
  Lock,
  Iphone,
  Search,
  Document,
  Refresh,
  Link,
  Key,
  AlarmClock,
  Location,
  Star,
  StarFilled,
  CircleClose,
  ShoppingCartFull,
  Tickets,
  PriceTag,
  Money,
} from "@element-plus/icons-vue";

/** 旧 iView type 字符串 → Element Plus 图标组件 */
export const ICON_MAP = {
  "md-checkmark": Check,
  "md-close": Close,
  "md-trash": Delete,
  "md-add": Plus,
  "md-arrow-dropdown": ArrowDown,
  "md-arrow-dropup": ArrowUp,
  "md-person": User,
  "md-lock": Lock,
  "md-phone-portrait": Iphone,
  "md-key": Key,
  "md-link": Link,
  "md-refresh": Refresh,
  "ios-arrow-down": ArrowDown,
  "ios-arrow-up": ArrowUp,
  "ios-arrow-forward": ArrowRight,
  "ios-arrow-back": ArrowLeft,
  "ios-arrow-round-down": ArrowDown,
  "ios-arrow-round-forward": ArrowRight,
  "ios-cart-outline": ShoppingCart,
  "ios-camera": Camera,
  "ios-eye-outline": View,
  "ios-trash-outline": Delete,
  "ios-alert-outline": Warning,
  "ios-help-circle-outline": Help,
  "ios-add-circle-outline": Plus,
  "ios-information-circle": InfoFilled,
  "ios-search": Search,
  "ios-text-outline": Document,
  "ios-alarm-outline": AlarmClock,
  "md-qr-scanner": Iphone,
  edit: Edit,
  "trash-a": Delete,
  location: Location,
  "ios-heart": StarFilled,
  "md-close-circle": CircleClose,
  "ios-cart": ShoppingCartFull,
  "md-clipboard": Tickets,
  "md-pricetag": PriceTag,
  "logo-usd": Money,
  "ios-eye": View,
  "md-star": Star,
};

export function resolveIcon(type) {
  return ICON_MAP[type] || InfoFilled;
}
