import { markRaw } from "vue";
import BASE_SETTING from "./setting/BASE_SETTING";
import GOODS_SETTING from "./setting/GOODS_SETTING";
import ORDER_SETTING from "./setting/ORDER_SETTING";
import POINT_SETTING from "./setting/POINT_SETTING";
import LOGISTICS_SETTING from "./setting/LOGISTICS_SETTING";
import OSS_SETTING from "./setting/OSS_SETTING";
import SMS_SETTING from "./setting/SMS_SETTING";
import IM_SETTING from "./setting/IM_SETTING";
import LIVE_SETTING from "./setting/LIVE_SETTING";
import WITHDRAWAL_SETTING from "./setting/WITHDRAWAL_SETTING";
import ALIPAY_PAYMENT from "./pay/ALIPAY_PAYMENT";
import WECHAT_PAYMENT from "./pay/WECHAT_PAYMENT";
import PAYMENT_SUPPORT from "./pay/PAYMENT_SUPPORT";
import WECHAT_CONNECT from "./authLogin/WECHAT_CONNECT";
import QQ_CONNECT from "./authLogin/QQ_CONNECT";
import CONNECT_SETTING from "./authLogin/CONNECT_SETTING";

export default {
  BASE_SETTING: markRaw(BASE_SETTING),
  GOODS_SETTING: markRaw(GOODS_SETTING),
  ORDER_SETTING: markRaw(ORDER_SETTING),
  POINT_SETTING: markRaw(POINT_SETTING),
  LOGISTICS_SETTING: markRaw(LOGISTICS_SETTING),
  OSS_SETTING: markRaw(OSS_SETTING),
  SMS_SETTING: markRaw(SMS_SETTING),
  IM_SETTING: markRaw(IM_SETTING),
  LIVE_SETTING: markRaw(LIVE_SETTING),
  WITHDRAWAL_SETTING: markRaw(WITHDRAWAL_SETTING),
  PAYMENT_SUPPORT: markRaw(PAYMENT_SUPPORT),
  WECHAT_PAYMENT: markRaw(WECHAT_PAYMENT),
  ALIPAY_PAYMENT: markRaw(ALIPAY_PAYMENT),
  WECHAT_CONNECT: markRaw(WECHAT_CONNECT),
  CONNECT_SETTING: markRaw(CONNECT_SETTING),
  QQ_CONNECT: markRaw(QQ_CONNECT),
};
