import { markRaw } from "vue";
import HOTWORD_SETTING from "./HOTWORD_SETTING";
import HOTWORDS_HISTORY from "./HOTWORDS_HISTORY";
import HOTWORDS_TODAY from "./HOTWORDS_TODAY";

export default {
  HOTWORD_SETTING: markRaw(HOTWORD_SETTING),
  HOTWORDS_TODAY: markRaw(HOTWORDS_TODAY),
  HOTWORDS_HISTORY: markRaw(HOTWORDS_HISTORY),
};
